// e2e-vision/autofix.ts
// Layer 3-4: Triage + Fix — GitHub Issue + Claude Code CLI auto-fix PR
// Usage: npx tsx autofix.ts [--dry-run] [--report ./results/analysis-report-xxx.json]

import * as fs from "fs/promises";
import { execSync, execFileSync } from "child_process";
import type { AnalysisReport, PageAnalysis } from "./analyze";

import { config as dotenvConfig } from "dotenv";
import * as path from "path";
dotenvConfig({ path: path.resolve(process.cwd(), ".env.test.local") });
dotenvConfig({ path: path.resolve(process.cwd(), "../.env.test.local") });

const CONFIG = {
  repoPath: process.env.REPO_PATH || "..",
  githubRepo: process.env.GITHUB_REPO || "kazooligan1982/zenshin-chart",
  slackWebhook: process.env.SLACK_WEBHOOK_URL || "",
  maxAutofix: 3,
  // Safety: only allow these tools in Claude Code CLI
  allowedTools: "Edit,Write,Bash(git *),Bash(npm run *),Bash(npx tsc *)",
};

async function createGitHubIssue(analysis: PageAnalysis, dryRun: boolean): Promise<string> {
  const criticals = analysis.issues.filter((i) => i.severity === "critical");
  const warnings = analysis.issues.filter((i) => i.severity === "warning");

  const body = [
    `## Auto-detected UI issues on \`${analysis.page}\` [${analysis.viewport}]`,
    `**Score**: ${analysis.overallScore}/100`,
    `**Summary**: ${analysis.summary}`,
    "",
    "### Critical Issues",
    ...criticals.map((i) => `- **${i.category}**: ${i.description}\n  Fix: ${i.suggestion}${i.filePath ? `\n  File: \`${i.filePath}\`` : ""}`),
    criticals.length === 0 ? "None" : "",
    "",
    "### Warnings",
    ...warnings.map((i) => `- **${i.category}**: ${i.description}\n  Fix: ${i.suggestion}`),
    warnings.length === 0 ? "None" : "",
    "",
    "---",
    "*Auto-generated by e2e-vision pipeline*",
  ].join("\n");

  const title = `[e2e-vision] ${analysis.page}[${analysis.viewport}]: ${analysis.summary}`;
  const titlePrefix = `[e2e-vision] ${analysis.page}[${analysis.viewport}]`;

  if (dryRun) {
    console.log(`    [DRY RUN] Would create issue: ${title}`);
    return "dry-run";
  }

  // Check for existing issue with same page+viewport prefix
  try {
    const existing = execFileSync(
      "gh",
      ["issue", "list", "--repo", CONFIG.githubRepo, "--label", "e2e-vision", "--search", titlePrefix, "--json", "title", "--limit", "5"],
      { encoding: "utf-8", cwd: CONFIG.repoPath }
    );
    const existingIssues = JSON.parse(existing) as Array<{ title: string }>;
    if (existingIssues.some((i) => i.title.startsWith(titlePrefix))) {
      console.log(`    Skipped (existing issue found for ${titlePrefix})`);
      return "existing";
    }
  } catch {}

  try {
    const result = execFileSync(
      "gh",
      [
        "issue", "create",
        "--repo", CONFIG.githubRepo,
        "--title", title.slice(0, 256),
        "--body-file", "-",
        "--label", "e2e-vision,bug",
      ],
      { encoding: "utf-8", cwd: CONFIG.repoPath, input: body }
    );
    const issueUrl = result.trim();
    console.log(`    Issue created: ${issueUrl}`);
    return issueUrl;
  } catch (e) {
    console.error(`    Failed to create issue:`, (e as Error).message);
    return "";
  }
}

async function runAutofix(analysis: PageAnalysis, issueUrl: string, dryRun: boolean): Promise<boolean> {
  const fixableIssues = analysis.issues.filter(
    (i) => i.severity === "critical" || i.severity === "warning"
  );
  if (fixableIssues.length === 0) return false;

  const issueDescription = fixableIssues
    .map((i) => `[${i.severity}] ${i.category}: ${i.description}. Fix: ${i.suggestion}${i.filePath ? ` File: ${i.filePath}` : ""}`)
    .join("\n");

  const branchName = `e2e-vision/fix-${analysis.page}-${analysis.viewport}-${Date.now()}`;

  const prompt = `Read QA_CONTEXT.md first. Then fix these UI issues found by automated testing on the ${analysis.page} page (${analysis.viewport} viewport):

${issueDescription}

IMPORTANT RULES:
- Both routes must be fixed: app/charts/[id] AND app/workspaces/[wsId]/charts/[id]
- Follow VRTA color conventions: V=emerald, R=orange, T=sky, A=slate
- Run npx tsc --noEmit to verify no type errors
- Create branch: ${branchName}
- Commit with message: fix: e2e-vision auto-fix ${analysis.page} [${analysis.viewport}]
- Push the branch

Related issue: ${issueUrl}`;

  if (dryRun) {
    console.log(`    [DRY RUN] Would run Claude Code CLI for ${fixableIssues.length} issues`);
    return false;
  }

  console.log(`    Running Claude Code CLI (${fixableIssues.length} issues)...`);
  try {
    execFileSync("git", ["checkout", "-b", branchName], { cwd: CONFIG.repoPath, stdio: "pipe" });
    execFileSync(
      "claude",
      ["--print", "--allowedTools", CONFIG.allowedTools],
      { cwd: CONFIG.repoPath, stdio: ["pipe", "inherit", "inherit"], input: prompt, timeout: 600000 }
    );

    // Create PR
    const prTitle = `[e2e-vision] Auto-fix: ${analysis.page} [${analysis.viewport}]`;
    const prBody = `Automated fix by e2e-vision pipeline.\n\nCloses ${issueUrl}`;
    execFileSync(
      "gh",
      ["pr", "create", "--repo", CONFIG.githubRepo, "--title", prTitle, "--body-file", "-", "--base", "develop"],
      { cwd: CONFIG.repoPath, stdio: ["pipe", "inherit", "inherit"], input: prBody }
    );

    // Return to develop
    execFileSync("git", ["checkout", "develop"], { cwd: CONFIG.repoPath, stdio: "pipe" });
    console.log(`    PR created for ${branchName}`);
    return true;
  } catch (e) {
    console.error(`    Autofix failed:`, (e as Error).message);
    try { execFileSync("git", ["checkout", "develop"], { cwd: CONFIG.repoPath, stdio: "pipe" }); } catch {}
    return false;
  }
}

async function notifySlack(report: AnalysisReport): Promise<void> {
  if (!CONFIG.slackWebhook) return;

  const text = [
    `:robot_face: *e2e-vision Report*`,
    `Score: ${report.averageScore}/100 | Issues: ${report.totalIssues} (${report.criticalCount} critical)`,
    ...report.analyses
      .filter((a) => a.issues.length > 0)
      .map((a) => `  ${a.overallScore >= 70 ? ":large_yellow_circle:" : ":red_circle:"} ${a.page}[${a.viewport}]: ${a.summary}`),
  ].join("\n");

  try {
    await fetch(CONFIG.slackWebhook, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });
  } catch (e) {
    console.error("Slack notification failed:", (e as Error).message);
  }
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes("--dry-run");

  let reportPath = args.find((a) => a.endsWith(".json"));
  if (!reportPath) {
    const files = await fs.readdir("./results");
    const reports = files.filter((f) => f.startsWith("analysis-report-")).sort().reverse();
    if (reports.length === 0) throw new Error("No analysis report found. Run analyze.ts first.");
    reportPath = `./results/${reports[0]}`;
  }

  console.log(`\n  Autofix: ${reportPath} ${dryRun ? "(DRY RUN)" : ""}`);
  const report: AnalysisReport = JSON.parse(await fs.readFile(reportPath, "utf-8"));

  await notifySlack(report);

  const pagesWithIssues = report.analyses.filter((a) => a.issues.some((i) => i.severity !== "info"));

  if (pagesWithIssues.length === 0) {
    console.log("  All clear!\n");
    return;
  }

  let fixAttempts = 0;
  let fixSuccesses = 0;
  let issueCount = 0;

  for (const analysis of pagesWithIssues) {
    console.log(`\n  ${analysis.page} [${analysis.viewport}] — Score: ${analysis.overallScore}/100`);
    const issueUrl = await createGitHubIssue(analysis, dryRun);
    issueCount++;

    if (fixAttempts < CONFIG.maxAutofix) {
      fixAttempts++;
      const fixed = await runAutofix(analysis, issueUrl, dryRun);
      if (fixed) fixSuccesses++;
    } else {
      console.log(`    Skipped autofix (max ${CONFIG.maxAutofix} attempts reached)`);
    }
  }

  console.log(`\n  Summary: ${issueCount} issues, ${fixSuccesses}/${fixAttempts} PRs ${dryRun ? "(dry run)" : ""}\n`);
}

main().catch((e) => { console.error("Fatal:", e); process.exit(1); });
